export const topics = [
    { value: 'aac', label: 'Art & Culture' },
    { value: 'ar', label: "Animals' rights" },
    { value: 'business', label: 'Business' },
    { value: 'cjs', label: 'Criminal Justice System' },
    { value: 'development', label: 'Development' },
    { value: 'economics', label: 'Economics' },
    { value: 'education', label: 'Education' },
    { value: 'entertainment', label: 'Entertainment'},
    { value: 'environment', label: 'Environment' },
    { value: 'family', label: 'Family' },
    { value: 'feminism', label: 'Feminism' },
    { value: 'freedoms', label: 'Freedoms' },
    { value: 'fiction', label: 'Fiction' },
    { value: 'funny', label: 'Funny' },
    { value: 'history', label: 'History' },
    { value: 'hr', label: 'Human Relationships' },
    { value: 'ir', label: 'International Relations' },
    { value: 'law', label: 'Law'},
    { value: 'lgbtqia+', label: 'LGBTQIA+' },
    { value: 'media', label: 'Media' },
    { value: 'me', label: 'Medical Ethics' },
    { value: 'mc', label: 'Minority Communities' },
    { value: 'morality', label: 'Morality' },
    { value: 'philosophy', label: 'Philosophy' },
    { value: 'politics', label: 'Politics' },
    { value: 'religion', label: 'Religion' },
    { value: 'sat', label: 'Science & Technology' },
    { value: 'swm', label: 'Security, War and Military' },
    { value: 'sp', label: 'Social Policy' },
    { value: 'sm', label: 'Social Movements' },
    { value: 'sports', label: 'Sports' },
    { value: 'terrorism', label: 'Terrorism' },
    { value: 'the', label: 'The Human Experience' },
    { value: 'others', label: 'Others' },
]
// module.exports = topics